---
AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 instance

Parameters:

  InstanceType:
    Description: Simple EC2 Instance
    Type: String
    Default: t2.micro
    AllowedValues: [t3.small, t3.medium, t1.micro, t2.nano, t2.micro, t2.small, t2.medium, t2.large, m1.small,
      m1.medium, m1.large, m1.xlarge, m2.xlarge, m2.2xlarge, m2.4xlarge, m3.medium,
      m3.large, m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge,
      m4.10xlarge, c1.medium, c1.xlarge, c3.large, c3.xlarge, c3.2xlarge, c3.4xlarge,
      c3.8xlarge, c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, g2.2xlarge,
      g2.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge, r3.8xlarge, i2.xlarge,
      i2.2xlarge, i2.4xlarge, i2.8xlarge, d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge,
      hi1.4xlarge, hs1.8xlarge, cr1.8xlarge, cc2.8xlarge, cg1.4xlarge]
    ConstraintDescription: must be a valid EC2 instance type.

  Subnet:
    Description: Choose a Subnet to deploy the Instance
    Type: AWS::EC2::Subnet::Id

  KeyName: 
    Description: KeyName to SSH Login
    Type: AWS::EC2::KeyPair::KeyName

  ImageId:
    Description: AMI name
    Type: String
    Default: ami-0e12cbde3e77cbb98

  SG:
    Description: Choose a SecurityGroupId
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds: 
        - !Ref SG
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub 
                    - |
                      #!/bin/bash
                      sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
                      sudo systemctl status amazon-ssm-agent
                      sudo systemctl enable amazon-ssm-agent
                      sudo systemctl start amazon-ssm-agent
                    - { valor: "x" }
      Tags:
        - Key: Name
          Value: EC2withSessionManager

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles:
        - !Ref EC2Role 
      InstanceProfileName: EC2InstanceProfile

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2RoleForSessionManager
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

